// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package searchtermsprotobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchClient interface {
	SearchTerms(ctx context.Context, in *SearchTermRequest, opts ...grpc.CallOption) (*SearchTermResponse, error)
	UpdateTerms(ctx context.Context, in *UpdateSearchTermsRequest, opts ...grpc.CallOption) (*UpdateSearchTermsResponse, error)
	GetSearchMetrics(ctx context.Context, in *SearchTermMetricsRequest, opts ...grpc.CallOption) (*SearchTermMetricsResponse, error)
}

type searchClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchClient(cc grpc.ClientConnInterface) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) SearchTerms(ctx context.Context, in *SearchTermRequest, opts ...grpc.CallOption) (*SearchTermResponse, error) {
	out := new(SearchTermResponse)
	err := c.cc.Invoke(ctx, "/searchtermsprotobuf.Search/SearchTerms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) UpdateTerms(ctx context.Context, in *UpdateSearchTermsRequest, opts ...grpc.CallOption) (*UpdateSearchTermsResponse, error) {
	out := new(UpdateSearchTermsResponse)
	err := c.cc.Invoke(ctx, "/searchtermsprotobuf.Search/UpdateTerms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) GetSearchMetrics(ctx context.Context, in *SearchTermMetricsRequest, opts ...grpc.CallOption) (*SearchTermMetricsResponse, error) {
	out := new(SearchTermMetricsResponse)
	err := c.cc.Invoke(ctx, "/searchtermsprotobuf.Search/GetSearchMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
// All implementations must embed UnimplementedSearchServer
// for forward compatibility
type SearchServer interface {
	SearchTerms(context.Context, *SearchTermRequest) (*SearchTermResponse, error)
	UpdateTerms(context.Context, *UpdateSearchTermsRequest) (*UpdateSearchTermsResponse, error)
	GetSearchMetrics(context.Context, *SearchTermMetricsRequest) (*SearchTermMetricsResponse, error)
	mustEmbedUnimplementedSearchServer()
}

// UnimplementedSearchServer must be embedded to have forward compatible implementations.
type UnimplementedSearchServer struct {
}

func (UnimplementedSearchServer) SearchTerms(context.Context, *SearchTermRequest) (*SearchTermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTerms not implemented")
}
func (UnimplementedSearchServer) UpdateTerms(context.Context, *UpdateSearchTermsRequest) (*UpdateSearchTermsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTerms not implemented")
}
func (UnimplementedSearchServer) GetSearchMetrics(context.Context, *SearchTermMetricsRequest) (*SearchTermMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSearchMetrics not implemented")
}
func (UnimplementedSearchServer) mustEmbedUnimplementedSearchServer() {}

// UnsafeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServer will
// result in compilation errors.
type UnsafeSearchServer interface {
	mustEmbedUnimplementedSearchServer()
}

func RegisterSearchServer(s grpc.ServiceRegistrar, srv SearchServer) {
	s.RegisterService(&Search_ServiceDesc, srv)
}

func _Search_SearchTerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SearchTerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/searchtermsprotobuf.Search/SearchTerms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SearchTerms(ctx, req.(*SearchTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_UpdateTerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSearchTermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).UpdateTerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/searchtermsprotobuf.Search/UpdateTerms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).UpdateTerms(ctx, req.(*UpdateSearchTermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_GetSearchMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTermMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).GetSearchMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/searchtermsprotobuf.Search/GetSearchMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).GetSearchMetrics(ctx, req.(*SearchTermMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Search_ServiceDesc is the grpc.ServiceDesc for Search service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Search_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "searchtermsprotobuf.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchTerms",
			Handler:    _Search_SearchTerms_Handler,
		},
		{
			MethodName: "UpdateTerms",
			Handler:    _Search_UpdateTerms_Handler,
		},
		{
			MethodName: "GetSearchMetrics",
			Handler:    _Search_GetSearchMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "searchterms.proto",
}
